services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.2
    container_name: redpanda
    networks:
      - redpanda_network
    ports:
      - 18082:18082
      - 19092:19092
      - 19644:9644
    volumes:
      - redpanda:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info

  console:
    image: docker.redpanda.com/redpandadata/console:v2.5.2
    container_name: console
    networks:
      - redpanda_network
    ports:
      - 8080:8080
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    depends_on:
      - redpanda

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    networks:
      - redpanda_network
    ports:
      - 5432:5432
    env_file:
      - ./apps/server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    networks:
      - redpanda_network
    ports:
      - 8081:8080
    restart: always
    env_file:
      - ./apps/server/.env
    depends_on:
      - redpanda
      - postgres

  api-gateway:
    container_name: api-gateway
    build:
      context: ./apps/server
      args:
        - APP=api-gateway
        - PORT=3000
    networks:
      - redpanda_network
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    command: pnpm dev api-gateway
    depends_on:
      - redpanda
      - postgres

  service-customer:
    container_name: service-customer
    build:
      context: ./apps/server
      args:
        - APP=service-customer
    networks:
      - redpanda_network
    working_dir: /app
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    command: pnpm dev service-customer
    depends_on:
      - redpanda
      - postgres

networks:
  redpanda_network:
    driver: bridge

volumes:
  redpanda: null
  postgres_data:
